language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

env:
  - JUST_INSTALL=1
  - SKIP_UPGRADE_TESTS=1

matrix:
    exclude:
        - php: 5.5
          env: JUST_INSTALL=1
        - php: 5.3
          env: JUST_INSTALL=1 

before_script: extras/dev/travis/before.sh

script: php tests/all_tests.php
